# -*- coding: utf-8 -*-

# "Vorwort" => VII
# "Inhaltsverzeichnis" => IX

PART = 0
CHAPTER = 1
SECTION = 2
EXKURS = 3

TOCLIST =
[
["EINLEITUNG", [1, PART]],
["I. Nationalökonomie und Praxeologie",  [1, SECTION]],
["II. Das Problem einer Wissenschaft vom menschlichen Handeln", 3],
["III. Nationalökonomie und Zielwahl", 7],
["IV. Zusammenfassung", 9],

["ERSTER TEIL: DAS HANDELN", [11, PART]],

["1. Kapitel: Der handelnde Mensch", [11, CHAPTER]],
["I. Handeln und unbewusste Reaktion",  [11, SECTION]],
["II. Die Vernunft im Handeln. Das Irrationale. Subjektivismus und Objektivität der Wissenschaft",  14],
["III. Der formale und apriorische Charakter der Lehre vom Handeln",  16],
["Exkurse: A. Über innere Erfahrung als vermeintliche Quelle praxeologischer Erkenntnis",  [17, 3]],
["B. Über den tautologischen Charakter der praxeologischen Deduktion",  19],
["C. Theorie und Erfahrung", 20],
["D. Über Kausalität", 22],
["IV. Eigenes und fremdes Handeln", [23, 2]],
["Exkurs: Über den Instinkt.", [29, 3]],
["V. Die allgemeinen Bedingungen des Handelns.", [30, 2]],

["2. Kapitel: Die Wissenschaft vom menschlichen Handeln",  [31, 1]],
["I. Der Ausgangspunkt der wissenschaftlichen Betrachtung des menschlichen Handelns: das Handeln der Einzelnen.", [31, 2]],
["Exkurs: Ich und Wir", [34, 3]],
["II. Der Ausgangspunkt der wissenschaftlichen Betrachtung des menschlichen Handelns: die einzelne Handlung.", [34, 2]],
["III. Einflüsse der Herkunft und der Umwelt auf das Handeln", 36],
["IV. Die Unwandelbarkeit der Struktur des Handelns", 37],
["V. Der logische Charakter der Praxeologie", 39],
["VI. Das praxeologische Problem.", 40],
["VII. Theorie und Geschichte. Qualitative und quantitative Erkenntnis",  42],
["VIII. Begreifen und Verstehen.", 51],
["IX. Praxeologischer Begriff und geisteswissenschaftlicher Typus", 56],
["X. Die Einheit der Wissenschaft", 60],
["XI. Praxeologischer Begriff und Wirklichkeit.", 63],
["XII. Die Grenzen der praxeologischen Begriffsbildung",  64],

["3. Kapitel: Die Kategorien des Handelns", [65, 1]],
["I. Ende, Ziel, Zweck. Mittel und Wege. Knappheit der Mittel. Freie Güter und wirtschaftliche Güter. Die Güterordnungen",  [65, 2]],
["Exkurse: A. Hedonismus, Eudämonismus, Utilitarismus", [68, 3]],
["B. Trieb und Triebsoziologie.", 69],
["C. Bedürfnis und Bedürfnislehre", 71],
["II. Das Vorziehen und die Rangordnung der Zwecke und der Mittel",  [72, 2]],
["Exkurs: Der nichthandelnde Mensch", [74, 3]],
["III. Das Handeln als Tausch. Wert und Preis. Kosten. Erfolg und Misserfolg. Gewinn und Verlust",  [75, 2]],

["4. Kapitel: Zeit und Handeln.", [76, 1]],
["I. Die Zeitlichkeit der Praxeologie",  [76, 2]],
["II. Vergangenheit, Gegenwart, Zukunft", 77],
["Exkurs: Das Denken modo futuri exacti", [80, 3]],
["III. Die Bewirtschaftung der Zeit",  [80, 2]],
["IV. Das Problem der Gleichzeitigkeit und die Vorstellung vermeintlich irrationalen Handelns",  81],

["5. Kapitel: Das Handeln in der Welt.", [84, CHAPTER]],
["I. Das Handeln und die Quantität und Qualität der Mittel. Das Grenznutzengesetz",  [84, SECTION]],
["II. Das Ertragsgesetz", 95],
["III. Die menschliche Arbeit als Mittel", 99],
["Exkurse: A. Mittelbarer und unmittelbarer Arbeitsgenuss",  [108, EXKURS]],
["B. Die bahnbrechende Leistung", 109],
["IV. Die Produktion", [111, SECTION]],

["ZWEITER TEIL: DAS HANDELN IN DER GESELLSCHAFT", [115, PART]],
["1. Kapitel: Die menschliche Gesellschaft", [115, CHAPTER]],
["I. Gesellschaft als Vereinigung menschlichen Handelns", [115, SECTION]],
["II. Kritik der universalistischen und kollektivistischen Gesellschaftsauffassung",  116],
["III. Die Arbeitsteilung", 125],
["IV. Das Ricardo’sche Vergesellschaftungsgesetz", 126],
["Exkurs: Missverständnisse in Bezug auf das Vergesellschaftungsgesetz", [129, EXKURS]],
["V. Wirkungen der Arbeitsteilung", [133, SECTION]],
["VI. Der Einzelne in der Gesellschaft", 134],
["Exkurs: Die Fabel von der Gemeinschaft.", [136, EXKURS]],
["VII. Gesellschaft als Tauschgesellschaft im weitesten Sinne", [139, SECTION]],
["VIII. Der Kampf- und Zerstörungstrieb.", 141],

["2. Kapitel: Die Idee im Handeln", [145, CHAPTER]],
["I. Die menschliche Vernunft", [145, SECTION]],
["II. Weltanschauung und Ideologie",  147],
["Exkurse: A. Die marxistische Ideologienlehre", [155, EXKURS]],
["B. Die rassenbiologische Variante des Polylogismus", 157],
["III. Idee, Macht, Gewalt, Herrschaft",  [166, SECTION]],
["Exkurse: A. Traditionsgebundenheit als Ideologie.", [171, EXKURS]],
["B. Der bildliche Gebrauch des Ausdruckes «Herrschaft»", 171],
["IV. Praxeologischer Subjektivismus und pseudohistorischer Relativismus", [172, SECTION]],
["V. Kritik der rassenbiologischen Gesellschafts- und Staatstheorie", 175],
["VI. Kritik des Fortschrittsoptimismus",  178],

["3. Kapitel: Der Tausch in der Gesellschaft", [180, CHAPTER]],
["I. Innerer Tausch und zwischenmenschlicher (gesellschaftlicher) Tausch", [180, SECTION]],
["II. Tauschgesellschaft und herrschaftlicher Verband", 182],
["III. Das Problem des rechnenden Handelns",  185],

["DRITTER TEIL: RECHNEN IM HANDELN", [188, PART]],
["1. Kapitel: Wertung ohne Rechnen.", [188, CHAPTER]],
["I. Die Reihung der Mittel", [188, SECTION]],
["II. Die Naturaltausch-Fiktion der elementaren Wert- und Preislehre", 189],
["Exkurs: Wertlehre und Sozialismus", [194, EXKURS]],
["III. Das Problem der Wirtschaftsrechnung", [195, SECTION]],
["VI. Wirtschaftsrechnung und Marktverkehr", 197],

["2. Kapitel: Die Geldrechnung, ihre Voraussetzungen und die Grenzen ihres Bereiches", [198, CHAPTER]],
["I. Die Geldansätze der Geldrechnung.", [198, SECTION]],
["II. Der Umfang der Geldrechnung.", 202],
["III. Die Wandelbarkeit der Geldpreise", 205],
["IV. Stabilisierung", 208],
["V. Die Herkunft der Stabilisierungsidee", 213],
["VI. Nebeneinanderbestehen mehrerer Geldarten", 217],

["3. Kapitel: Die Geldrechnung als gedankliches Werkzeug des Handelns", [218, CHAPTER]],
["I. Die Geldrechnung als Denkverfahren. Der Begriff des Wirtschaftlichen im engeren Sinne", [218, SECTION]],
["II. Geldrechnung und Praxeologie", 220],

["VIERTER TEIL: DIE MARKTWIRTSCHAFT", [224, PART]],
["1. Kapitel: Problemstellung und Verfahren der Katallaktik", [224, CHAPTER]],
["I. Die Abgrenzung des katallaktischen Problemkreises", [224, SECTION]],
["II. Die Methode der Gedankenbilder", 227],
["III. Das Gedankenbild der reinen Marktwirtschaft.", 228],
["Exkurs: Die Maximalisierung der Gewinne.", [231, EXKURS]],
["IV. Das Gedankenbild der einfachen Wirtschaft", [234, SECTION]],
["V. Die Gedankenbilder des einfachen und des endlichen Ruhezustandes und der gleichmässigen Wirtschaft", 235],
["VI. Das Gedankenbild der stationären Wirtschaft", 243],
["VII. Das Problem einer nationalökonomischen Dynamik", 244],
["VIII. Das Gedankenbild der funktionell gegliederten Marktwirtschaft", 245],
["Exkurs: Die Unternehmerfunktion in der stationären Wirtschaft", [249, EXKURS]],

["2. Kapitel: Die Steuerung des Handelns durch den Markt", [250, CHAPTER]],
["I. Das Wesen der Marktwirtschaft.", [250, SECTION]],
["II. Kapitalrechnung und Kapital; Realkapital und Geldkapital", 253],
["III. Kapitalismus", 256],
["IV. Unternehmer und Verbraucher", 258],
["Exkurs: Die Ausgabenwirtschaft des Unternehmers.", [260, EXKURS]],
["V. Der Wettbewerb", [261, SECTION]],
["VI. Gewinn und Verlust der Unternehmer", 265],
["VII. Die Auslese des Marktes", 271],
["VIII. Erzeuger und Verbraucher", 273],
["IX. Die Werbung", 277],
["X. Die Wirte und die Volkswirtschaft", 280],

["3. Kapitel: Die Preise", [283, CHAPTER]],
["I. Die Preisbildung auf dem Markte", [283, SECTION]],
["II. Wertung und Preisbildung", 289],
["III. Die Preise der Güter höherer Ordnung.", 291],
["Exkurs: Eine Grenze der Preisbildung der Produktionsmittel", [300, EXKURS]],
["IV. Die Kostenrechnung", [301, SECTION]],
["V. Der Menger-Böhm’sche Weg zur Lösung des Zurechnungsproblems und die mathematische Katallaktik", 312],
["VI. Die Monopolpreise.", 319],
["Exkurs: Die mathematische Behandlung der Monopolpreislehre", [335, EXKURS]],
["VII. Die Kundschaft", [337, SECTION]],
["VIII. Die Preisgestaltung beim Nachfragemonopol.", 341],
["IX. Der Verbrauch unter dem Einfluss der Monopolpreise", 343],
["X. Die Diskriminationspreise", 346],
["XI. Der Zusammenhang der Preise", 350],
["XII. Die Preise und die Einkommensbildung", 352],
["XIII. Die Preise und die Ordnung der Produktion", 354],

["4. Kapitel: Der indirekte Tausch", [356, CHAPTER]],
["I. Tauschmittel und Geld", [356, SECTION]],
["II. Bemerkungen über einige Irrwege der Geldtheorie", 356],
["III. Geldvorrat und Geldbedarf; Nachfrage nach Geld und Angebot an Geld", 360],
["Exkurs: Die methodologische Bedeutung der Menger’schen Lehre vom Ursprung des Geldes", [365, EXKURS]],
["IV. Die Gestaltung der Kaufkraft des Geldes", [368, SECTION]],
["V. Das Hume-Mill’sche Problem und die Triebkraft des Geldes", 375],
["VI. Veränderungen der Kaufkraft von der Geldseite her und von der Warenseite her", 379],
["VII. Kaufkraftänderungen und Geldrechnung", 383],
["VIII. Das Geld im Kreditverkehr", 385],
["IX. Der Einfluss erwarteter Kaufkraftänderungen auf die Gestaltung der Kaufkraft", 385],
["X. Der spezifische Geldwert und der Gelddienst", 389],
["XI. Die Geldsurrogate: Geldzertifikate und Umlaufsmittel", 392],
["XII. Die Grenzen der Umlaufsmittelausgabe", 394],
["Exkurs: Bemerkungen zur Diskussion über Bankfreiheit", [404, EXKURS]],
["XIII. Die Grösse der Kassenbestände der einzelnen Wirte", [406, SECTION]],
["XIV. Die Zahlungsbilanzen", 409],
["XV. Die Paritäten", 412],
["XVI. Die Zinsfussarbitrage und die Diskontpolitik der Notenbanken", 417],
["XVII. Sekundäre Tauschmittel, ", 419],
["XVIII. Die inflationistische Geschichtsauffassung", 423],
["XIX. Die Goldwährung", 428],

["5. Kapitel: Das Handeln im Ablauf der Zeit", [434, CHAPTER]],
["I. Die verschiedene Schätzung gleichlanger Zeitabschnitte.", [434, SECTION]],
["Exkurs: Bemerkungen zu Böhm-Bawerks Lehre von der Höherwertung gegenwärtiger Güter", [439, EXKURS]],
["II. Der praxeologische Beweis für die Höhenwertung zeitlich näherer Befriedigung", [443, SECTION]],
["III. Die Kapitalgüter", 449],
["IV. Produktionszeit, Wartezeit, Vorsorgezeit.", 452],
["Exkurs: Erstreckung der Vorsorgezeit über die erwartete Lebensdauer hinaus", [458, EXKURS]],
["V. Die Lenkbarkeit der Kapitalgüter", [459, SECTION]],
["VI. Das Kapital als Träger einer Einwirkung der Vergangenheit auf Produktion und Verbrauch", 463],
["VII. Kapitalersatz, Kapitalneubildung, Kapitalaufzehrung", 467],
["VIII. Geld und Kapital; Sparen und Investieren.", 471],

["6. Kapitel: Der Zins.", [474, CHAPTER]],
["I. Die Zinserscheinung.", [474, SECTION]],
["II. Der Urzins", 476],
["III. Die Höhe des Zinses.", 484],
["IV. Der Urzins in der ungleichmässigen Wirtschaft", 485],
["V. Die Zinsrechnung", 487],

["7. Kapitel: Geldzins, Kreditausweitung und Konjunkturwechsel", [488, CHAPTER]],
["I. Die Probleme der Geldzinslehre", [488, SECTION]],
["II. Die Risikokomponente im Bruttozins", 489],
["III. Die Preisprämie im Bruttozins", 492],
["IV. Der Darlehensmarkt", 496],
["V. Die Veränderungen des Geldstands und die Gestaltung des Urzinses", 498],
["VI. Der Marktzins unter dem Einfluss von Veränderungen des Geldstands im Fall der Inflation und der Kreditausweitung", 500],
["VII. Der Marktzins unter dem Einfluss von Veränderungen des Geldstands im Fall der Restriktion", 514],
["VIII. Die Zirkulationskredittheorie des Konjunkturwechsels", 518],
["IX. Die Marktwirtschaft im Wechsel der Konjunktur", 521],
["Exkurse: A. Die Rolle der unbeschäftigten Produktionsmittel im Anfangstadium des Aufschwungs", [527, EXKURS]],
["B. Bemerkungen über Versuche, den Konjunkturwechsel nicht monetär zu erklären", 529],

["8. Kapitel: Arbeit und Lohn", [532, CHAPTER]],
["I. Innenarbeit und Aussenarbeit", [532, SECTION]],
["II. Arbeitsfreude und Arbeitsqual", 537],
["III. Der Arbeitslohn", 540],
["IV. Die Arbeitslosigkeit", 546],
["V. Die Lohnbildung: die Ansprüche der Käufer von Arbeit", 548],
["VI. Die Lohnbildung: die Ansprüche der Verkäufer von Arbeit", 550],
["VII. Das Arbeitsleid und das Angebot an Arbeit.", 556],
["VIII. Das Unternehmerrisiko des Arbeiters", 563],
["XI. Der Arbeitsmarkt", 565],
["Exkurs: Die Arbeit der Tiere und der Sklaven", [568, EXKURS]],

["9. Kapitel: Die aussermenschlichen ursprünglichen Produktionsfaktoren", [574, CHAPTER]],
["I. Bemerkungen zur Rententheorie", [574, SECTION]],
["II. Die Unzerstörbarkeit der Bodenkräfte", 577],
["III. Der Überfluss an Boden", 580],
["IV. Der Boden als Standort", 582],
["V. Die Bodenpreise", 583],
["Exkurs: Der Mythus vom Boden", [584, EXKURS]],

["10. Kapitel: Die Daten der Marktlage", [585, CHAPTER]],
["I. Das Gegebene und das Datum", [585, SECTION]],
["II. Die Macht als Datum", 588],
["III. Die Gewalt als Datum", 590],
["IV. Der leibhaftige Mensch als Datum.", 592],
["V. Die Reaktionszeit. Wirkungen in the long run und in the short run", 597],
["VI. Die Grenzen des Sondereigentums und das Problem der external costs and external economies", 599],
["Exkurse: A. Über das Eigentum an Rezepten.", [604, EXKURS]],
["B. Privilegien", 605],

["11. Kapitel: Einklang und Widerstreit der Interessen", [605, CHAPTER]],
["I. Die Quelle der Gewinne auf dem Markte.", [605, SECTION]],
["II. Die Geburtenregelung", 608],
["III. Die Harmonie der «richtig verstandenen» Interessen.", 614],
["IV. Das Sondereigentum", 621],
["V. Die Konflikte der modernen Welt.", 624],

["FÜNFTER TEIL: DIE VERKEHRSLOSE ARBEITSTEILIGE WIRTSCHAFT", [628, PART]],
["1. Kapitel: Das Gedankenbild einer verkehrslosen arbeitsteiligen Wirtschaft", [628, CHAPTER]],
["I. Die Herkunft des planwirtschaftlichen Gedankens", [628, SECTION]],
["II. Das praxeologische Wesen der Gemeinwirtschaft", 632],

["2. Kapitel: Die Unmöglichkeit sozialistischer Wirtschaftsrechnung", [634, CHAPTER]],
["I. Die Lösungsversuche", [634, SECTION]],
["II. Die Aufgabe", 636],
["III. Der künstliche Markt", 638],
["IV. Die Gleichungen der mathematischen Katallaktik", 641],

["SECHSTER TEIL: DIE GEHEMMTE MARKTWIRTSCHAFT", [646, PART]],
["1. Kapitel: Markt und Obrigkeit.", [646, CHAPTER]],
["I. Eine dritte Lösung", [646, SECTION]],
["II. Der Eingriff", 647],
["III. «Gerechtigkeit» als Richtmass des Handelns", 649],
["IV. Die Obrigkeit.", 654],
["V. Die Obrigkeit und die Zielwahl.", 654],

["2. Kapitel: Die steuerpolitischen Eingriffe", [657, CHAPTER]],
["I. Die neutrale Steuer", [657, SECTION]],
["II. Die totale Steuer", 659],
["III. Finanzpolitische und sozialpolitische Ziele der Besteuerung", 660],
["IV. Die drei Abarten der steuerpolitischen Eingriffe", 662],

["3. Kapitel: Die produktionspolitischen Eingriffe", [663, CHAPTER]],
["I. Das Wesen des produktionspolitischen Eingriffs", [663, SECTION]],
["II. Erfolg und Kosten des Eingriffs", 664],
["III. Der Eingriff als Privileg.", 665],
["IV. Der produktionspolitische Eingriff als Aufwand", 666],

["4. Kapitel: Die preispolitischen Eingriffe", [668, CHAPTER]],
["I. Die Alternative: Macht oder ökonomisches Gesetz", [668, SECTION]],
["II. Die Reaktion des Marktes auf preispolitische Eingriffe", 672],
["Exkurs: Einige Worte über die Ursachen des Unterganges des antiken Kultur", [677, EXKURS]],

["5. Kapitel: Die währungs- und bankpolitischen Eingriffe", [679, CHAPTER]],
["I. Interventionistische Währungspolitik", [679, SECTION]],
["II. Die Schuldenabbürdung", 682],
["III. Die Abwertung", 685],
["IV. Die Kreditausweitung.", 692],
["V. Devisenbewirtschaftung und Clearingverträge", 697],

["6. Kapitel: Konfiskation und Redistribution", [700, CHAPTER]],
["I. Die ausgleichende Gerechtigkeit in der Landwirtschaft", [700, SECTION]],
["II. Die Konfiskation durch Besteuerung", 703],
["III. Die Beschränkung des nicht aus Arbeit stammenden Ertrags", 704],

["7. Kapitel: Ständestaat und Syndikalismus", [705, CHAPTER]],
["I. Die neue ständische Idee", [705, SECTION]],
["II. Die politische Verfassung des Ständestaats", 708],
["III. Die Wirtschaftsverfassung des Korporativismus", 711],
["IV. Syndikalismus", 715],

["8. Kapitel: Die Krise des Interventionismus", [717, CHAPTER]],
["I. Die Beweiskraft der Tatsachen", [717, SECTION]],
["II. Arbeitslosigkeit, das Schicksalproblem der Zeit.", 720],

["9. Kapitel: Kriegswirtschaft", [723, CHAPTER]],
["I. Der Krieg und die Marktwirtschaft", [723, SECTION]],
["II. Heereskrieg und totaler Krieg", 725],
["III. Die totale Mobilmachung", 727],
["IV. Kriegswirtschaftliche Autarkie", 730],
["V. Das Problem des letzten Krieges", 737],

["SCHLUSSWORT", [740, CHAPTER]],
["I. Die Wissenschaft und das Leben", [740, SECTION]],
["II. Die Wissenschaft und die Politik", 743],
["III. Die Wissenschaft und die Zukunft", 750]

# ["Sachregister", 752]
]
